name: Verificar projeto

on:
  push:
  pull_request:

jobs:
  verificar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Verificar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Executar agenda
        run: python agenda.py